<a href="https://colab.research.google.com/github/mdrehantabish123/mdrehantabish123-Data_Science_Lab_SE_A_38/blob/main/Experiment_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

First, let's import the `numpy` library and define a sample square matrix. We will then calculate its determinant.

In [8]:
import numpy as np

# a) Create a 3x3 matrix and find determinant
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10]])

print("Matrix A:")
print(A)

det = np.linalg.det(A)
print("\nDeterminant of A:", det)

# b) Find inverse of the matrix
if det != 0:
    A_inv = np.linalg.inv(A)
    print("\nInverse of Matrix A:")
    print(A_inv)
else:
    print("\nInverse does not exist")

# c) Solve system of equations:
# 2x + 3y = 10
# 4x + 5y = 20

B = np.array([[2, 3],
              [4, 5]])

C = np.array([10, 20])

solution = np.linalg.solve(B, C)
print("\nSolution of equations (x, y):")
print(solution)


Matrix A:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

Determinant of A: -2.9999999999999996

Inverse of Matrix A:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]

Solution of equations (x, y):
[5. 0.]
