<a href="https://colab.research.google.com/github/mdrehantabish123/mdrehantabish123-Data_Science_Lab_SE_A_38/blob/main/experiment3(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create 3x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10]])

print("Matrix A:")
print(A)

# -------- Determinant of 3x3 Matrix --------
det = (
    A[0][0]*(A[1][1]*A[2][2] - A[1][2]*A[2][1])
    - A[0][1]*(A[1][0]*A[2][2] - A[1][2]*A[2][0])
    + A[0][2]*(A[1][0]*A[2][1] - A[1][1]*A[2][0])
)

print("\nDeterminant of A:", det)


# -------- Inverse of Matrix --------
if det != 0:

    # Calculate the adjugate matrix
    adj = np.zeros((3,3))

    # Cofactors for the first row
    adj[0][0] = (A[1][1]*A[2][2] - A[1][2]*A[2][1])
    adj[0][1] = -(A[1][0]*A[2][2] - A[1][2]*A[2][0])
    adj[0][2] = (A[1][0]*A[2][1] - A[1][1]*A[2][0])

    # Cofactors for the second row
    adj[1][0] = -(A[0][1]*A[2][2] - A[0][2]*A[2][1])
    adj[1][1] = (A[0][0]*A[2][2] - A[0][2]*A[2][0])
    adj[1][2] = -(A[0][0]*A[2][1] - A[0][1]*A[2][0])

    # Cofactors for the third row
    adj[2][0] = (A[0][1]*A[1][2] - A[0][2]*A[1][1])
    adj[2][1] = -(A[0][0]*A[1][2] - A[0][2]*A[1][0])
    adj[2][2] = (A[0][0]*A[1][1] - A[0][1]*A[1][0])

    # Transpose the matrix of cofactors to get the adjugate
    adj = adj.T

    # Calculate the inverse
    inverse = adj / det

    print("\nInverse of Matrix A:")
    print(inverse)

else:
    print("\nInverse does not exist (determinant is zero).")


# -------- Solve Equations using Cramer's Rule --------
# For equations: a1x + b1y = c1
#                a2x + b2y = c2

a1, b1, c1 = 2, 3, 10
a2, b2, c2 = 4, 5, 20

# Calculate the determinants
D = a1*b2 - a2*b1
Dx = c1*b2 - c2*b1
Dy = a1*c2 - a2*c1

# Check if D is zero (no unique solution)
if D != 0:
    x = Dx / D
    y = Dy / D

    print("\nSolution of equations:")
    print("x =", x)
    print("y =", y)
else:
    print("\nCannot solve equations using Cramer's Rule: Determinant D is zero.")

Matrix A:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

Determinant of A: -3

Inverse of Matrix A:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]

Solution of equations:
x = 5.0
y = -0.0
